### ISSUE TITLE
Cannot resolve dependency '@beyonk/svelte-mapbox' in svelte3-parcel-starter

### ISSUE THREAD

**Issue by bebopxff** [beyonk-adventures/svelte-mapbox#1]
After installed @beyonk/svelte-mapbox in [svelte3-parcel-starter](https://github.com/edm00se/svelte3-parcel-starter.git) via `yarn add @beyonk/svelte-mapbox`, got an error message `Cannot resolve dependency '@beyonk/svelte-mapbox'`. How can i fix it?

Version:

@beyonk/svelte-mapbox 2.2.3

**Comment by antony** [comment]
@bebopxff it sounds like your yarn command hasn't correctly added the dependency to your project. I don't know much about yarn so I'm not sure how to help other than to suggest you look in the yarn docs for how to add a dependency?

It needs to be added as a `dependency` not a `devDependency` for a Svelte project.
