### ISSUE TITLE
<Marker> was created without expected prop 'lng'

### ISSUE THREAD

**Issue by nfk** [beyonk-adventures/svelte-mapbox#12]
2 parameters are expected about longitude to initialize a Marker. `lon` or `lng` see https://github.com/beyonk-adventures/svelte-mapbox/blob/1041b7f165d07f9b04b9203a3cd29fae1cf1d777/src/Marker.svelte#L29. This leads to a console warning `<Marker> was created without expected prop 'lng'`

**Comment by antony** [comment]
Interesting, I'm not sure at all why this change was made.

**Comment by antony** [comment]
Looks like I tried to support `lon || lng` and messed it up. Serves me right for not having any tests.

Fixed in v5.0.0
