### ISSUE TITLE
event

### ISSUE THREAD

**Issue by chun49** [beyonk-adventures/svelte-mapbox#19]
on:click can not be used at Map component

**Comment by GenieTim** [comment]
I suppose you should be able to use the events listed here: https://docs.mapbox.com/mapbox-gl-js/api/map/#map-events

For example, in the script section of the example in the [README](https://github.com/beyonk-adventures/svelte-mapbox/blob/master/README.md) you could use:

```javascript
mapComponent.on('click', (e) => { console.log(e.lngtlat); })
```
