### ISSUE TITLE
Any change Marker lat lng does not reflect in mapbox

### ISSUE THREAD

**Issue by the-yadu** [beyonk-adventures/svelte-mapbox#23]
Marker lat lng updates as expected once when it is rendered for the first time.
Marker does not update if its lat and lng props are changed or modified.

Is there a special way to do it or its not handled?

I can raise PR if required.

**Comment by the-yadu** [comment]
#24

**Comment by antony** [comment]
I've released v6.0.0 which incorporates your ideas, but takes them a step further. Hope you enjoy!

**Comment by the-yadu** [comment]
Thank you so much... I love it... binding 👍
