### ISSUE TITLE
Can someone add a license for the repository?

### ISSUE THREAD

**Issue by sbutler-gh** [beyonk-adventures/svelte-mapbox#27]
Thank you guys so much for providing this resource.

Can one of the maintainers/project owners add a license?  I would like to explore building with this, but I don't want to override any permissions in doing so.

**Comment by antony** [comment]
Heya.

The license is MIT.

If this doesn't work for you, please let me know and I'll consider other options.

**Comment by sbutler-gh** [comment]
That works @antony, just wanted to make sure.  Thanks so much for the quick response on this!
