### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by zberwaldt** [beyonk-adventures/svelte-mapbox#3]
```
Error: Cannot find module 'C:\...\node_modules\@beyonk\svelte-mapbox\index.mjs'. Please verify that the package.json has a valid "main" entry
```
I am attempting to use this component in Sapper, but when I try to import it I get the above error. Let me know if you need additional information.

**Comment by antony** [comment]
@zberwaldt can you tell me how you're installing the project?

I built the project for / and use it with Sapper, and it works fine for me, so not sure what you're seeing here.

**Comment by zberwaldt** [comment]
Ah! Then this was definitely user error. Apologies, I will close this issue. Thank you for your help!
