### ISSUE TITLE
Custom markers

### ISSUE THREAD

**Issue by Amerlander** [beyonk-adventures/svelte-mapbox#33]
I try to add a Marker with custom element.

The `element` property seems not to be usable:
`<Marker element={myImage}  lat=0 lng=0 />`

`Marker.svelte:51 <Marker> was created with unknown prop 'element'`

Is this a missing feature, or do I something wrong?

**Comment by evdama** [comment]
Hi folks... kinda the same question:

- I've `svelte-mapbox` running fine with a Sapper project
- now I want to give my markers and popups a custom style... hm... ok... how do I do that?
- I found those two mapbox doc sites but then that's basically pure HTML & JS styling, not with svelte and svelte-mapbox
-- https://docs.mapbox.com/mapbox-gl-js/api/markers/
-- https://docs.mapbox.com/help/tutorials/custom-markers-gl-js/

So my question basically is, how do I do what's mentioned at https://docs.mapbox.com/help/tutorials/custom-markers-gl-js/ in my `svelte-mapbox` code which atm looks like this:

```html
    <div class="flex flex-row justify-center">
      <div class="rounded-lg mapboxgl-map">
        <Map
          accessToken="pk.eyJ1IjoibWFya3VzZ2F0dG9sIiwiYSI6ImNrbT... some API key...QghnXJ0SEUR"
          bind:this={ mapComponent }
          on:ready={ onReady }
          on:zoom={ () => { console.log('zooming...') } }
          on:recentre={ onRecentre }
          options={{ zoom: 4 }}
        >
          <Marker bind:lat={ $userStore.userPrimaryAddress.userAddress.metadata.latitude }
                  bind:lng={ $userStore.userPrimaryAddress.userAddress.metadata.longitude }
                  color="{ toHSL( $session.clientSessionID ) }"
                  label="{ $userStore.userDisplayName }"
                  popupOffset = 100
                  closeButton = false
                  popupClassName="edm-marker-popup" />
          <NavigationControl />
          <ScaleControl />
          <GeolocateControl options={{ some: 'control-option' }} on:eventname={ mapboxEventHandler } />
        </Map>
      </div>
    </div>
```

**Comment by antony** [comment]
So I think this is two questions with different answers:

@Amerlander can you create a REPL to demonstrate the issue please?

@evdama I would just create a custom marker svelte component and add that to the map instead of <Marker />.
you can use the existing Marker component as a guide.

**Comment by Amerlander** [comment]
I was just trying to use the "element" property as described in the mapbox api documentation: https://docs.mapbox.com/mapbox-gl-js/api/markers/
![image](https://user-images.githubusercontent.com/3764089/111664603-3c74ab80-8812-11eb-86e5-485615f15bbd.png)

Since it just isnt suported in this component I came up with a PR (https://github.com/beyonk-adventures/svelte-mapbox/pull/34).
This way I can use html or subcomponents as markers and style them with css:
```svelte
          {#each mainPoint.waypoints as waypoint}
            <Marker
            popup={false}
            lat={waypoint.geo.lat}
            lng={waypoint.geo.lng}
            > 
              <a href={waypoint.slug}>
                <div class='myMarker pph {($mapData.activeMarker == waypoint.id) ? 'active' : ''}' 
                style="
                color:{mainPoint.color};
                background-image: url('{(waypoint.images != undefined) ? waypoint.images[0].thumb.url : ''}');
                ">
                </div>
              </a>
            </Marker>
          {/each}
```
which results in this (plus some css):
![image](https://user-images.githubusercontent.com/3764089/111664550-2c5ccc00-8812-11eb-860a-81f90e7e1512.png)

Note: Using `on:mouseover` doesnt work  in the marker compoonent, since it seem to be consumed by the parent `<Map>` component itself. But I havent looked into that anymore. I just stick to css `:hover`.

**Comment by evdama** [comment]
Oh... this is lovely 🤩 
Looks reasonable to me having HTML inside the `<Marker/>` component, at least maybe to prototype things before moving on to some custom marker component if needed or desired.

**Comment by CraigChamberlain** [comment]
Is it a good idea to use the Slot for this?  I thought that might be better for the content of the popup?

**Comment by CraigChamberlain** [comment]
Looking at the custom popup, it looks like its setup to except a string so I've made an optional prop that handles that.
#37

**Comment by Amerlander** [comment]
In my perspective the popup is just a subpart (or sub component) of the actual marker.
So I think it makes sense to use the slot for this. 

It could also make sense to be able to specify html for the popup like with named slots like this:
```svelte
<div bind:this={elementMarker}>
  <slot></slot>
</div>

<div bind:this={elementPopup}>
  <slot name="popup"></slot>
</div>
```

Your PR https://github.com/beyonk-adventures/svelte-mapbox/pull/37/ looks very similar to https://github.com/beyonk-adventures/svelte-mapbox/pull/26 or did I miss something?

**Comment by CraigChamberlain** [comment]
Funny. We did exactly  the same thing.  The named slot sounds good. There
is another pr dealing with custom pin and they fancied using the slot too.

**Comment by Amerlander** [comment]
I tried implementing the named slot, but somehow failed and since I had no time to look further I reverted my changes in the PR https://github.com/beyonk-adventures/svelte-mapbox/pull/34 …

**Comment by CraigChamberlain** [comment]
What do you think of implications of using a <Link /> inside a customPopup?

Would be nice not to have to force a full reload and use routing if
possible.  Problem is the Marker requires a string not a Svelte component.
Can you force a component  to be rendered down to an html string?

**Comment by Amerlander** [comment]
>  Problem is the Marker requires a string not a Svelte component. Can you force a component to be rendered down to an html string?

Well, that seemed to be my issue, I put in the component instead of a string. I use `.innerHTML`  now to get the string out of it.

Created another PR with additional named slot for popup: https://github.com/beyonk-adventures/svelte-mapbox/pull/38

Thank you @antony for merging #34. I think #38 might be a useful addition.
