### ISSUE TITLE
Map is not reacting on zoom or center change

### ISSUE THREAD

**Issue by LucianVoju** [beyonk-adventures/svelte-mapbox#35]
As stated in the description map should react ro zoom or center change via bindings.
After first paint if zoom or center is modified map is not reacting.
Here [REPL](https://svelte.dev/repl/5ccef1b397024334b0f628aeb8da5e3b?version=3.23.2)

Thank you

**Comment by antony** [comment]
The map responds to dragging to set the centre. We tested and confirmed this a few days ago.

Zoom is not currently bound, but happy to accept a PR to allow the zoom binding to happen.

**Comment by LucianVoju** [comment]
Hello,

Made a PR, home it's ok. https://github.com/beyonk-adventures/svelte-mapbox/pull/36

Thank you

**Comment by antony** [comment]
Released as v7.5.0 :) thanks!
