### ISSUE TITLE
Error when using with Svelte Kit

### ISSUE THREAD

**Issue by LucianVoju** [beyonk-adventures/svelte-mapbox#44]
Hello,
I have this error when using with Svelte Kit:
'/node_modules/fastq/queue.js?v=607b44ec' does not provide an export named 'default'

Thanks

**Comment by christippett** [comment]
I had a similar issue. Adding `fastq` to the list of included dependencies in `svelte.config.cjs` is what got it working for me.

```js
module.exports = {

  ...

  kit: {
    vite: {
      optimizeDeps: {
        include: ["fastq"] // 👈
      }
    }
  }
}
```

**Comment by antony** [comment]
Looks like we need an equivalent to fastq or for fastq to become an esm module.

**Comment by antony** [comment]
I've raised https://github.com/mcollina/fastq/issues/44
