### ISSUE TITLE
Get access to map object

### ISSUE THREAD

**Issue by the-yadu** [beyonk-adventures/svelte-mapbox#5]
How to get access to map object to use mapbox additional funcitionality such as flyto?

Also how to import Marker component?

**Comment by antony** [comment]
To import a marker:

```jsx
import controls from '@beyonk/svelte-mapbox'
const { Marker } = controls

<Marker />
```

To get an instance of the map, your best bet right now is to create a custom component and place it inside the map - and expose the map, something like:

```js

// MyCustomComponent.svelte
<script>
  import { getContext } from 'svelte'
  import { contextKey } from '@beyonk/svelte-mapbox'

  const { getMap } = getContext(contextKey)

  export let map = getMap()
</script>

<MyCustomComponent bind:map={map} />

// then map.blah()
```

However this is a workaround - I should expose the `getMap` method, and I will do as soon as I have a minute.

**Comment by the-yadu** [comment]
Sure, Thanks for a quick reply.

access to map object is something I can wait for.
Meanwhile, I can send a pull request to expose flyTo functionality so that I can use it.

**Comment by the-yadu** [comment]
I have implemented flyto functionality and updated readme. Can you add me to project so that I can raise a pull request?

**Comment by antony** [comment]
@the-yadu you don't need to be part of the project to raise a pull request - just raise it :)

**Comment by antony** [comment]
Fixed in v4.x.x
