### ISSUE TITLE
Marker is not exported

### ISSUE THREAD

**Issue by kidandcat** [beyonk-adventures/svelte-mapbox#7]

**Comment by antony** [comment]
Thanks!

https://github.com/beyonk-adventures/svelte-mapbox/commit/7c9412557215a179eff0b154411e9f223ab1f47b

**Comment by kidandcat** [comment]
I edited in github, so I couldn't run prepublish, could you make a build?

**Comment by antony** [comment]
@kidandcat it's all automated :) you just have to wait a minute or so

**Comment by antony** [comment]
Spoke too soon - try version v4.0.2 :)
